# Generated by Django 3.2.4 on 2022-01-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enmodel',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
